aws_images/albums/urls.py
from django.urls import path
from .views import AlbumsListView, AlbumsCreateView, AlbumsDetailView

app_name = 'albums'

urlpatterns = [
    path('', AlbumsListView.as_view(), name='list'),
    path('create/', AlbumsCreateView.as_view(), name='create'),
    path('<int:pk>/detail', AlbumsDetailView.as_view(), name='detail')
]

aws_images/aws_images/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('albums/', include('albums.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aws_images/albums/models.py
from django.db import models
from django.shortcuts import redirect

# Create your models here.


class Album(models.Model):
    title = models.CharField(max_length=50, blank=False, null=False)
    description = models.TextField()
    bucket = models.CharField(max_length=100, null=False, blank=False)
    key_path = models.CharField(max_length=100, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return '{}'.format(redirect('albums:list').url)

aws_images/albums/forms.py
from .models import Album
from django.forms import ModelForm


class AlbumsForm(ModelForm):
    class Meta:
        model = Album
        fields = ['title', 'description']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['title'].widget.attrs.update({
            'class': 'form-control',
            'id': 'title',
            'placeholder': 'Titulo'
        })

        self.fields['description'].widget.attrs.update({
            'class': 'form-control',
            'id': 'description',
            'placeholder': 'Titulo'
        })




aws_images/albums/views.py
from django.shortcuts import render
from .models import Album
from django.views.generic import ListView, CreateView, DetailView
from .forms import AlbumsForm

# Create your views here.


class AlbumsListView(ListView):
    model = Album
    template_name = 'albums/list.html'
    paginate_by = 10

    def get_context_data(self, *args, **kwargs):
        form = AlbumsForm()
        context = super().get_context_data(*args, **kwargs)
        context['form'] = form

        return context


class AlbumsCreateView(CreateView):
    model = Album
    form_class = AlbumsForm


class AlbumsDetailView(DetailView):
    model = Album
    template_name = 'albums/detail.html'

aws_images/albums/templates/albums/detail.html
{% extends 'base/base.html' %}
{% block content %}
    <div class="row">
        <div class="col">
            {{ object }}
        </div>
    </div>
{% endblock %}

aws_images/albums/templates/albums/list.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

    {% include 'snippets/modal_form.html' %}

    <div class="row">
        <div class="col">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#albumModal">
                Nuevo Álbum
            </button>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <table class="table mt-5">
                <thead class="table-light">
                <tr>
                    <th scope="col">Titulo</th>
                    <th scope="col">Fecha creación</th>
                    <th scope="col">Items</th>
                    <th scope="col">Size</th>
                </tr>
                </thead>
                <tbody>
                {% for album in album_list %}
                    <tr>
                        <td>
                            <a href="{% url 'albums:detail' album.id %}">{{ album.title }}</a>
                        </td>
                        <td>{{ album.created_at }}</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    {% include 'snippets/paginator.html' %}

{% endblock %}

aws_images/albums/templates/snippets/modal_form.html
<!-- Modal -->
<div class="modal fade" id="albumModal" tabindex="-1" aria-labelledby="albumModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="albumModalLabel">Modal title</h5>
                <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'albums:create' %}" method="post">
                {% csrf_token %}
                <div class="modal-body">
                    {% for field in form %}
                        <div class="form-group">
                            {{ field }}
                        </div>
                    {% endfor %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <input class="btn btn-primary" type="submit" value="Submit">
                </div>
            </form>
        </div>
    </div>
</div>





aws_images/albums/templates/snippets/paginator.html
{% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li>
                <span><a href="?page={{ page_obj.previous_page_number }}">Previous</a></span>
            </li>
        {% endif %}
        <li class="">
            <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
        </li>
        {% if page_obj.has_next %}
            <li>
                <span><a href="?page={{ page_obj.next_page_number }}">Next</a></span>
            </li>
        {% endif %}
    </ul>
{% endif %}

aws_images/templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}"/>

    <title>Hello, world!</title>
</head>
<body>
<div class="container pt-5">
    <div class="row">
        <div class="col">
            {% block content %}{% endblock %}
        </div>
    </div>
</div>


<script src="https://kit.fontawesome.com/8aa938375a.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>